version: "3.8"

services:
  snapper:
    image: ghcr.io/natankeddem/snapper:latest
    ports:
      - 8080:8080
    volumes:
      - ~/path/to/data:/app/data
      - ~/path/to/logs:/app/logs
    environment:
      - PUID=1000
      - PGID=1000
      - VERBOSE_LOGGING=TRUE # Optional