version: "3.8"

services:
  bale:
    image: ghcr.io/natankeddem/bale:latest
    ports:
      - 8080:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/path/to/data:/app/data
      - ~/path/to/logs:/app/logs
    environment:
      - PUID=1000
      - PGID=1000
      - VERBOSE_LOGGING=TRUE # Optional